version: '3'

services:
    kafka:
        image: wurstmeister/kafka:1.1.0
        expose:
        - "9092"
        environment:
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        depends_on:
        - zookeeper
    zookeeper:
        image: wurstmeister/zookeeper
        expose:
        - "2181"
    dataflow-server:
        image: springcloud/spring-cloud-dataflow-server-local:1.6.1.RELEASE
        container_name: dataflow-server
        ports:
        - "9393:9393"
        - "9000-9010:9000-9010"
        environment:
        - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers=kafka:9092
        - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes=zookeeper:2181
        depends_on:
        - kafka
        volumes:
        - ~/.m2:/root/.m2
